# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_autor_fecha_nac1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='fecha_nac1',
        ),
    ]
