# -*- coding: utf-8 -*-
<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 1.10.3 on 2016-11-04 18:13
=======
# Generated by Django 1.10.3 on 2016-11-04 17:26
>>>>>>> 8ca5d9d1b554e7dc56beab57b192995165ada4c0
=======
# Generated by Django 1.10.3 on 2016-11-04 20:14
>>>>>>> 43184a8c69e03ecd0de6ede1e96e86ad34ad42e4
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
<<<<<<< HEAD
            name='PeriodoContable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('codigo', models.CharField(blank=True, max_length=15, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fechInicio', models.DateField(blank=True, null=True)),
                ('fechFin', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'PeriodoContables',
                'permissions': (('list_periodoContable', 'Can list periodoContable'), ('get_periodoContable', 'Can get periodoContable')),
                'verbose_name': 'PeriodoContable',
=======
=======
            name='Cajaingreso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=60)),
                ('cuentaEmpresa', models.IntegerField(default=170)),
                ('cuentaCliente', models.IntegerField(default=170)),
                ('cuentaGanancia', models.IntegerField(default=170)),
                ('cuentaVenta', models.IntegerField(default=170)),
                ('entregadoA', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha', models.DateTimeField(blank=True, max_length=60, null=True)),
                ('sucursal', models.IntegerField(default=170)),
                ('total', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cajaingresos',
                'verbose_name': 'Cajaingreso',
            },
        ),
        migrations.CreateModel(
>>>>>>> 43184a8c69e03ecd0de6ede1e96e86ad34ad42e4
            name='Usercashier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.CharField(max_length=20)),
                ('perfil', models.CharField(max_length=20)),
                ('sucursal', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Usercashiers',
                'permissions': (('list_usercashier', 'Can list usercashier'), ('get_usercashier', 'Can get usercashier')),
<<<<<<< HEAD
>>>>>>> 8ca5d9d1b554e7dc56beab57b192995165ada4c0
=======
                'verbose_name': 'Usercashier',
>>>>>>> 43184a8c69e03ecd0de6ede1e96e86ad34ad42e4
            },
        ),
    ]
