# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=170)),
                ('detalle', models.CharField(max_length=40)),
                ('precioUn', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('igv', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('precioTotal', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'permissions': (('list_boleta', 'Can list boleta'), ('get_boleta', 'Can get boleta')),
                'verbose_name': 'Boleta',
                'verbose_name_plural': 'Boletas',
            },
        ),
        migrations.CreateModel(
            name='Cajaingreso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=60)),
                ('cuentaEmpresa', models.IntegerField(default=170)),
                ('cuentaCliente', models.IntegerField(default=170)),
                ('cuentaGanancia', models.IntegerField(default=170)),
                ('cuentaVenta', models.IntegerField(default=170)),
                ('entregadoA', models.CharField(blank=True, max_length=60, null=True)),
                ('sucursal', models.IntegerField(default=170)),
                ('total', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'Cajaingreso',
                'verbose_name_plural': 'Cajaingresos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('docIdentidad', models.CharField(max_length=16)),
                ('direccion', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Modcontable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contanual', models.CharField(blank=True, max_length=50, null=True)),
                ('regisanual', models.CharField(max_length=50)),
            ],
            options={
                'permissions': (('list_modcontable', 'Can list modcontable'), ('get_modcontable', 'Can get modcontable')),
                'verbose_name': 'Modcontable',
                'verbose_name_plural': 'Modcontables',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombreSuc', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
                ('telforno', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
            },
        ),
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('codigo', models.CharField(blank=True, max_length=15, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fechInicio', models.DateField(blank=True, null=True)),
                ('fechFin', models.DateField(blank=True, null=True)),
            ],
            options={
                'permissions': (('list_periodoContable', 'Can list periodoContable'), ('get_periodoContable', 'Can get periodoContable')),
                'verbose_name': 'PeriodoContable',
                'verbose_name_plural': 'PeriodoContables',
            },
        ),
        migrations.CreateModel(
            name='Usercashier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.CharField(max_length=20)),
                ('perfil', models.CharField(max_length=20)),
                ('sucursal', models.CharField(max_length=20)),
            ],
            options={
                'permissions': (('list_usercashier', 'Can list usercashier'), ('get_usercashier', 'Can get usercashier')),
                'verbose_name': 'Usercashier',
                'verbose_name_plural': 'Usercashiers',
            },
        ),
        migrations.AddField(
            model_name='boleta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.Cliente'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.Nivel'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='usercashiers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.Usercashier'),
        ),
    ]
