# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombreSuc', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
                ('telforno', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Niveles',
                'verbose_name': 'Nivel',
            },
        ),
    ]
