# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caja.Cliente'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caja.Nivel'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='usercashiers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caja.Usercashier'),
        ),
    ]
