# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_cajaingreso_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cajaingreso',
            options={'permissions': (('list_cajaingreso', 'Can list cajaingreso'), ('get_cajaingreso', 'Can get cajaingreso')), 'verbose_name': 'Cajaingreso', 'verbose_name_plural': 'Cajaingresos'},
        ),
    ]
