# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_auto_20161124_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
