# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_boleta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
